# Generated by Django 5.1.2 on 2025-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicData',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField()),
            ],
        ),
    ]
